const products = [{
    id: `1`,
    marca: `Apple`,
    modelo: `iPhone14`,
    color: `Morado`,
    memoriaInterna: `128`,
    memoriaRam: `6`,
    camara: `48`,
    precio: `484141`,
    category: `Celulares`,
    img: `https://i.ibb.co/1ZpJYSd/iPhone14.png`,
    stock: `5`
},
{
    id: `2`,
    marca: `Samsung`,
    modelo: `GalaxyA13`,
    color: `Celeste`,
    memoriaInterna: `64`,
    memoriaRam: `4`,
    camara: `50`,
    precio: `74999`,
    category: `Celulares`,
    img: `https://i.ibb.co/wSRYCjr/Galaxy-A13.png`,
    stock: `6`
},
{
    id: `3`,
    marca: `Motorola`,
    modelo: `MotoE20`,
    color: `Aqua`,
    memoriaInterna: `32`,
    memoriaRam: `4`,
    camara: `13`,
    precio: `37999`,
    category: `Celulares`,
    img: `https://i.ibb.co/KLfHyJ3/MotoE20.png`,
    stock: `3`
},
{
    id: `4`,
    marca: `Apple`,
    modelo: `iPad 10 - A2696`,
    color: `Azul`,
    pantalla: `10.9”`,
    resolución: `2360px x 1640px`,
    memoriaInterna: `64`,
    memoriaRam: `4`,
    cámara: `12`,
    precio: `234499`,
    category: `Tablets`,
    img: `https://i.ibb.co/4Mf9PCv/i-Pad-10th.png`,
    stock: `3`
},
{
    id: `5`,
    marca: `Xiaomi`,
    modelo: `Pad 5`,
    color: `Cosmic gray`,
    pantalla: `11”`,
    resolución: `2560 px x 1600 px`,
    memoriaInterna: `128`,
    memoriaRam: `6`,
    cámara: `13`,
    precio: `243999`,
    category: `Tablets`,
    img: `https://i.ibb.co/4ZvzZGv/Xiaomi-Pad5.png`,
    stock: `4`
},
{
    id: `6`,
    marca: `Apple`,
    modelo: `iPad 10 - A2696`,
    color: `Rosa`,
    pantalla: `10.9”`,
    resolución: `2360px x 1640px`,
    memoriaInterna: `256`,
    memoriaRam: `4`,
    cámara: `12`,
    precio: `317499`,
    category: `Tablets`,
    img: `https://i.ibb.co/PWG6swT/i-Pad-10th-RS.png`,
    stock: `2`
},
{
    id: `7`,
    marca: `Asus`,
    modelo: `G513RM`,
    color: `Eclipse gray`,
    pantalla: `15.6 "`,
    resolución: `2560 px x 1440 px`,
    procesador: `Ryzen 7`,
    grafica: `NVIDIA RTX 3060`,
    almacenamiento: `512`,
    memoriaRam: `16`,
    precio: `715999`,
    category: `Laptops`,
    img: `https://i.ibb.co/R7zjyyx/Asus-Rog-Strix-G15-G513-RM.png`,
    stock: `3`
},
{
    id: `8`,
    marca: `Asus`,
    modelo: `FX506LHB`,
    color: `Bonfire black`,
    pantalla: `15.6 "`,
    resolución: `1920 px x 1080 px`,
    procesador: `Intel Core i5`,
    grafica: `NVIDIA GeForce GTX 1650`,
    almacenamiento: `512`,
    memoriaRam: `16`,
    precio: `378099`,
    category: `Laptops`,
    img: `https://i.ibb.co/VNdRQj5/Asus-TUF-FX506-LHB.png`,
    stock: `6`
},
{
    id: `9`,
    marca: `MSI`,
    modelo: `GL66`,
    color: `Negro`,
    pantalla: `16”`,
    resolución: `1920 px x 1080 px`,
    procesador: `Intel Core i7`,
    grafica: `NVIDIA GeForce RTX 3070`,
    almacenamiento: `512`,
    memoriaRam: `16`,
    precio: `905000`,
    category: `Laptops`,
    img: `https://i.ibb.co/Y0DDpzJ/Msi-Gl66-11-ugk-001.png`,
    stock: `4`
},
{
    id: `10`,
    marca: `Samsung`,
    modelo: `C27RG50FQ`,
    pantalla: `27”`,
    resolución: `1920 px x 1080 px`,
    tipoPantalla: `LED`,
    frecuencia: `240`,
    tiempoRespuesta: `4`,
    precio: `131599`,
    category: `Monitores`,
    img: `https://i.ibb.co/v14tbj5/Samsung-CRG5.png`,
    stock: `9`
},
{
    id: `11`,
    marca: `Redragon`,
    modelo: `GM270F165`,
    pantalla: `27”`,
    resolución: `1920 px x 1080 px`,
    tipoPantalla: `LED`,
    frecuencia: `165`,
    tiempoRespuesta: `4`,
    precio: `110.999`,
    category: `Monitores`,
    img: `https://i.ibb.co/6Pd4v8T/Redragon-Emerald-GM270-F165.png`,
    stock: `7`
},    
{
    id: `12`,
    marca: `Samsung`,
    modelo: `F27T350FHL`,
    pantalla: `27"`,
    resolución: `1920 px x 1080 px`,
    tipoPantalla: `LED`,
    frecuencia: `75`,
    tiempoRespuesta: `5`,
    precio: `68.909`,
    category: `Monitores`,
    img: `https://i.ibb.co/mRQQgtn/Samsung-F27-T350-FHL.png`,
    stock: `4`
}
]

export const getProducts = () => {
return new Promise ((resolve) => {
    setTimeout(() => {
        resolve(products)
    }, 2000)
})
}